export const CREATE_USER = 'CREATE_USER';
export const UPDATE_USER = 'UPDATE_USER';

export const REQUEST_MUSICS = 'REQUEST_MUSICS';
export const GET_MUSICS_SUCCESS = 'GET_MUSICS_SUCCESS';
export const GET_MUSICS_ERROR = 'GET_MUSICS_ERROR';

export const ADD_FAVORITE_SONG = 'ADD_FAVORITE_SONG';
export const REMOVE_FAVORITE_SONG = 'REMOVE_FAVORITE_SONG';
